apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-strta-demo-app
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-strta-demo-app
  template:
    metadata:
      labels:
        app: kubernetes-strta-demo-app
    spec:
      containers:
      - name: kubernetes-strta-demo-app
        image: kubernetes-strta-demo/app:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MY_CUSTOM_ENV
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: MY_CUSTOM_ENV
          - name: MY_CUSTOM_SECRET
            valueFrom:
              secretKeyRef:
                name: demo-secret
                key: mySecretFile
        ports:
          - name: api
            containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: api
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: api
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-strta-demo-app-service
  labels:
    app: kubernetes-strta-demo-app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: api
  selector:
    app: kubernetes-strta-demo-app
