apiVersion: v1
kind: LimitRange
metadata:
  name: kubernetes-strta-demo-resource-limits
spec:
  limits:
  - max:
      cpu: 1000m
      memory: 1Gi
    min:
      cpu: 1000m
      memory: 0.5Gi
    type: Pod
  - default:
      cpu: 1000m
      memory: 0.5Gi
    defaultRequest:
      cpu: 1000m
      memory: 0.5Gi
    max:
      cpu: 2000m
      memory: 2Gi
    min:
      cpu: 1000m
      memory: 0.5Gi
    type: Container
